{% set name = "sketch" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sketch-{{ version }}.tar.gz
  sha256: 45bfd2d41ad4939a0c8ad8ad86cef00ea1709a5e3c4c32e2ed20d255c0a09b9f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - pandas >=1.3.0
    - datasketch >=1.5.8
    - datasketches >=4.0.0
    - ipython
    - lambdaprompt >=0.5.4
    - packaging

test:
  imports:
    - sketch
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Compute, store and operate on data sketches
  home: https://github.com/approximatelabs/sketch
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
